version: '3.8'

services:
  discovery-service:
    build: ./Backend/discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - smarttransit-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  gateway-service:
    build: ./Backend/gateway-service
    container_name: gateway-service
    ports:
      - "8080:8081"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - smarttransit-network

  auth-service:
    build: ./Backend/auth-service
    container_name: auth-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - smarttransit-network

  geolocation-service:
    build: ./Backend/geolocation-service
    container_name: geolocation-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - smarttransit-network

  notification-service:
    build: ./Backend/notification-service
    container_name: notification-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - smarttransit-network

  payment-service:
    build: ./Backend/payment-service
    container_name: payment-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - smarttransit-network

  route-service:
    build: ./Backend/route-service
    container_name: route-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - smarttransit-network

  subscription-service:
    build: ./Backend/subscription-service
    container_name: subscription-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - smarttransit-network

  ticket-service:
    build: ./Backend/ticket-service
    container_name: ticket-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - smarttransit-network

  trip-service:
    build: ./Backend/trip-service
    container_name: trip-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - smarttransit-network

  user-service:
    build: ./Backend/user-service
    container_name: user-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - smarttransit-network

  vehicle-service:
    build: ./Backend/vehicle-service
    container_name: vehicle-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - smarttransit-network

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway-service
    networks:
      - smarttransit-network

networks:
  smarttransit-network:
    driver: bridge
